### PR TITLE
Multiple Fixes for the ModPrefabCache

### LINKED ISSUE #394: Issue with duplicate cache items
**Describe the bug**
With some prefabs, several duplicate GameObjects get added to the prefab cache. Seems to happen before a game is even loaded, and maybe with prefabs that have non-matching TechTypes and Class IDs.

**Expected behavior**
One instance max per cache object.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by MrPurple6411**
### Changes made in this pull request

  - Added a ModPrefabRequest Cache to call upon so that it is not making multiple requests anymore.
  - Null Check ProcessPrefabAsync
  - Add prefab name to error log when missing PrefabIdentifier

### Breaking changes

  - Should be none.

### CODE REVIEW

**Comment by 32Kallies** [comment]
This seems fine for now, should be ready to merge, but it would probably be best to make a system that uses existing prefab requests for “work in progress” prefabs rather than running multiple requests at the same time.

File: Nautilus/Assets/ModPrefabCache.cs [hunk 1]
```diff
@@ -89,27 +90,24 @@ private void Awake()
...
-        if (!Entries.ContainsKey(prefabIdentifier.classId))
+        // Proper prefabs can never exist in the scene, so parenting them is dangerous and pointless. 
+        if (prefab.IsPrefab())
+        {
+            InternalLogger.Debug($"Game Object: {prefab} is a proper prefab. Skipping parenting for cache.");
+        }
+        else if(!Entries.ContainsKey(prefabIdentifier.classId))
         {
+            prefab.transform.parent = _prefabRoot;
+            prefab.SetActive(true);
```
Comment (Metious) [inline Nautilus/Assets/ModPrefabCache.cs]: While this appears to be much better than before and won't always just add an entry to the cache without much checks, I think clashing and duplicates is still possible, but it's now just "less" likely.

I suggest testing the example mod. that one has a duplicate on the copper clone iirc.

File: Nautilus/Handlers/PrefabHandler.cs [hunk 2]
```diff
@@ -69,7 +76,18 @@ private static IEnumerator ProcessPrefabAsync(GameObject obj, PrefabInfo info, P
         if (Prefabs.TryGetPostProcessorForInfo(info, out var postProcessor))
             yield return postProcessor?.Invoke(obj);
 
-        ModPrefabCache.AddPrefab(obj);
+
+        if (ModPrefabCache.TryGetPrefabFromCache(info.ClassID, out var obj2))
+        {
+            gameObject.Set(obj2);
+            GameObject.Destroy(obj);
```
Comment (Metious) [inline Nautilus/Handlers/PrefabHandler.cs]: This looks dangerous. Since non-instantiated asset bundle prefabs can be custom prefabs, wouldn't destroying a prefab would make the current one also null?

**Review by Metious — COMMENTED** [review]
Added a few comments

File: Nautilus/Handlers/PrefabHandler.cs (hunk 2 above)
Comment (MrPurple6411) [reply Nautilus/Handlers/PrefabHandler.cs]: > This seems fine for now, should be ready to merge, but it would probably be best to make a system that uses existing prefab requests for “work in progress” prefabs rather than running multiple requests at the same time.

> This looks dangerous. Since non-instantiated asset bundle prefabs can be custom prefabs, wouldn't destroying a prefab would make the current one also null?

Ohh ooohhhhhhhh   brain explosion..... 

Forgot that addressables Cache their request calls so as not to duplicate them.

I need to add a modPrefabRequest cache and it will fix both of these issues.

Thanx guys.

**Review by Metious — APPROVED** [review]
lgtm
